#!/usr/bin/env python3
"""Generate the bundled gobo/IES preset library deterministically.

Every asset here is synthetic and made by this script (no third-party gobo
artwork or manufacturer photometry), so the library is free to redistribute.

Writes:
  internal/presets/presets.json          (source of truth, embedded by Go)
  addon/thornbury_lighting/presets/*     (images, .ies files, presets.json copy)

Usage: python3 tools/gen_presets.py   (needs numpy + Pillow; only run by developers)
"""
import json
import math
import os
import shutil

import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ADDON_DIR = os.path.join(ROOT, "addon", "thornbury_lighting", "presets")
GO_JSON = os.path.join(ROOT, "internal", "presets", "presets.json")
N = 512

yy, xx = np.mgrid[0:N, 0:N]
u = (xx + 0.5) / N  # 0..1 left->right
v = 1.0 - (yy + 0.5) / N  # 0..1 bottom->top (Blender image convention)


def smoothstep(e0, e1, x):
    t = np.clip((x - e0) / (e1 - e0), 0, 1)
    return t * t * (3 - 2 * t)


def save(name, a):
    a = np.clip(a, 0, 1)
    Image.fromarray((a * 255).round().astype(np.uint8), "L").save(os.path.join(ADDON_DIR, name), optimize=True)


def value_noise(seed, cells):
    rng = np.random.default_rng(seed)
    g = rng.random((cells + 1, cells + 1))
    x, y = u * cells, v * cells
    i, j = np.floor(x).astype(int), np.floor(y).astype(int)
    fx, fy = smoothstep(0, 1, x - i), smoothstep(0, 1, y - j)
    a, b = g[j, i], g[j, i + 1]
    c, d = g[j + 1, i], g[j + 1, i + 1]
    return (a * (1 - fx) + b * fx) * (1 - fy) + (c * (1 - fx) + d * fx) * fy


def gobos():
    r = np.hypot(u - 0.5, v - 0.5)
    # Venetian blinds: 9 horizontal slats, ~55% open, slightly soft edges.
    phase = (v * 9) % 1.0
    save("gobo_window_blinds.png", smoothstep(0.40, 0.46, phase) * (1 - smoothstep(0.94, 1.0, phase)))
    # Four-pane window: soft mullion cross plus frame.
    bar = lambda t, c, w: smoothstep(w, w + 0.012, np.abs(t - c))
    panes = bar(u, 0.5, 0.018) * bar(v, 0.5, 0.018)
    frame = smoothstep(0.08, 0.095, u) * smoothstep(0.08, 0.095, 1 - u) * smoothstep(0.08, 0.095, v) * smoothstep(0.08, 0.095, 1 - v)
    save("gobo_window_panes.png", panes * frame)
    # Leaf breakup: two octaves of smooth noise, thresholded into dappled light.
    n = 0.65 * value_noise(7, 9) + 0.35 * value_noise(11, 23)
    save("gobo_leaf_breakup.png", smoothstep(0.50, 0.58, n))
    # Soft iris: a round pool that is tighter than the cone, with a soft edge.
    save("gobo_soft_iris.png", 1 - smoothstep(0.22, 0.34, r))
    # Slot: barn doors closed top and bottom, leaving a soft horizontal band.
    save("gobo_slot.png", 1 - smoothstep(0.10, 0.16, np.abs(v - 0.5)))


# Peak candela chosen so a preset keeps the light's centre brightness: Cycles
# scales IES output by 0.0770 per candela in Blender 4.2-4.5 and 0.0707 in
# 5.0-5.2 (measured with float renders, tools/render_presets.py). 13.54 cd is
# the geometric mean, giving a centre gain of 1.04 (4.x) / 0.96 (5.x), about
# +/-0.06 stops. A 1000 cd peak made presets ~70x (6 stops) too bright.
IES_PEAK_CD = 13.54


def write_ies(name, label, falloff):
    """LM-63-2002, type C photometry, rotationally symmetric.
    Vertical angle 0 is straight along the beam (nadir)."""
    angles = list(range(0, 181, 5))
    cd = [round(IES_PEAK_CD * falloff(math.radians(a)), 4) for a in angles]
    lines = [
        "IESNA:LM-63-2002",
        "[TEST] synthetic profile generated by tools/gen_presets.py",
        "[MANUFAC] Thornbury VFX demo library (synthetic, not a real fixture)",
        f"[LUMCAT] {name}",
        f"[LUMINAIRE] {label}",
        "TILT=NONE",
        f"1 -1 1 {len(angles)} 1 1 2 0 0 0",
        "1 1 0",
        " ".join(str(a) for a in angles),
        "0",
        " ".join(str(c) for c in cd),
    ]
    with open(os.path.join(ADDON_DIR, name + ".ies"), "w", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")


def ies():
    gauss = lambda half: (lambda t: math.exp(-0.5 * (t / half) ** 2))
    write_ies("ies_narrow_spot", "Narrow spot (~20 degree beam)", gauss(math.radians(8.5)))
    write_ies("ies_medium_soft", "Medium soft beam (~45 degree)", gauss(math.radians(19)))
    write_ies("ies_wide_flood", "Wide flood (~90 degree field, soft shoulder)", lambda t: max(0.0, math.cos(t)) ** 3)


PRESETS = [
    {"id": "gobo_window_blinds", "kind": "gobo", "label": "Window blinds", "file": "gobo_window_blinds.png", "extension": "REPEAT",
     "use_when": "breaks the beam into horizontal slat shadows, like light through venetian blinds"},
    {"id": "gobo_window_panes", "kind": "gobo", "label": "Window panes", "file": "gobo_window_panes.png", "extension": "EXTEND",
     "use_when": "projects a four-pane window frame, like sunlight through a window"},
    {"id": "gobo_leaf_breakup", "kind": "gobo", "label": "Leaf breakup", "file": "gobo_leaf_breakup.png", "extension": "REPEAT",
     "use_when": "dappled, broken-up light, like light through foliage; breaks up a flat wash"},
    {"id": "gobo_soft_iris", "kind": "gobo", "label": "Soft iris", "file": "gobo_soft_iris.png", "extension": "EXTEND",
     "use_when": "a soft round pool tighter than the cone; a snoot-like cut with a feathered edge"},
    {"id": "gobo_slot", "kind": "gobo", "label": "Slot (barn doors)", "file": "gobo_slot.png", "extension": "EXTEND",
     "use_when": "cuts the beam top and bottom into a horizontal band, like closing barn doors"},
    {"id": "ies_narrow_spot", "kind": "ies", "label": "Narrow spot profile", "file": "ies_narrow_spot.ies",
     "use_when": "a hot centre with fast falloff inside the cone (about 20 degree beam)"},
    {"id": "ies_medium_soft", "kind": "ies", "label": "Medium soft profile", "file": "ies_medium_soft.ies",
     "use_when": "an even beam with a gentle shoulder (about 45 degrees)"},
    {"id": "ies_wide_flood", "kind": "ies", "label": "Wide flood profile", "file": "ies_wide_flood.ies",
     "use_when": "broad flood whose brightness rolls off gently toward the edge of a wide cone (about 90 degree field)"},
]


def main():
    os.makedirs(ADDON_DIR, exist_ok=True)
    gobos()
    ies()
    doc = {"version": 1, "presets": PRESETS}
    os.makedirs(os.path.dirname(GO_JSON), exist_ok=True)
    with open(GO_JSON, "w", newline="\n") as fh:
        json.dump(doc, fh, indent=2)
        fh.write("\n")
    shutil.copyfile(GO_JSON, os.path.join(ADDON_DIR, "presets.json"))
    print("wrote", len(PRESETS), "presets to", ADDON_DIR)


if __name__ == "__main__":
    main()
